<?php

namespace AppBundle\Repository;

/**
 * AlumnoCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
